# Generated by Django 3.2.7 on 2021-12-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharacterRole',
            new_name='Role',
        ),
        migrations.AddField(
            model_name='character',
            name='roles',
            field=models.ManyToManyField(to='character_api.Role'),
        ),
        migrations.AlterModelTable(
            name='character',
            table='character',
        ),
    ]
