# Generated by Django 3.2.7 on 2021-12-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_api', '0003_auto_20211210_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='alignment',
            field=models.CharField(blank=True, choices=[('Lawful Good', 'Lg'), ('Neutral Good', 'Ng'), ('Chaotic Good', 'Cg'), ('Lawful Neutral', 'Ln'), ('Neutral', 'Nn'), ('Chaotic Neutral', 'Cn'), ('Lawful Evil', 'Le'), ('Neutral Evil', 'Ne')], max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
    ]
